stages:
  - test
  - deploy

python35:
  stage: test
  image: python:3.5
  before_script:
  - pip install -r requirements.txt
  script:
  - make test

python36:
  stage: test
  image: python:3.6
  before_script:
  - pip install -r requirements.txt
  script:
  - make test

python37:
  stage: test
  image: python:3.7
  before_script:
  - pip install -r requirements.txt
  script:
  - make test

python38:
  stage: test
  image: python:3.8
  before_script:
  - pip install -r requirements.txt
  script:
  - make test

twine:
  stage: deploy
  image: python:3.8
  before_script:
    - pip install -r requirements.txt
  script:
    - python setup.py sdist bdist_wheel
    - twine upload -u $PYPI_USERNAME -P $PYPI_PASSWORD dist/
  only:
    - tags
